# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89232a500dff6cdf99b2ebd5e29de315b1328343ef081766ae32a36eb21904d9a17306fd3cd312f4ada53fd8ec3dfeaf7776de0c09d4a1b7adef8c61f340a2d5

test:
  secret_key_base: e3cc480dd2ec088bd7abb356f182a410061daa901655973ee8e53c4fcc15ccbec7a898cf55f5ddb3c2da2c7d54a065a4708c8f4bea75a6c4419e269d99585792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
